<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-04-10T14:58:57Z" name="suite" finished-at="2018-04-10T15:06:17Z" duration-ms="439641">
    <groups>
    </groups>
    <test started-at="2018-04-10T14:58:57Z" name="Test" finished-at="2018-04-10T15:06:17Z" duration-ms="439641">
      <class name="Test.Test1">
        <test-method is-config="true" signature="launching()[pri:0, instance:Test.Test1@38d8f54a]" started-at="2018-04-10T18:04:50Z" name="launching" finished-at="2018-04-10T18:04:52Z" duration-ms="1646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching -->
        <test-method signature="FirstTask()[pri:0, instance:Test.Test1@38d8f54a]" started-at="2018-04-10T18:04:52Z" name="FirstTask" finished-at="2018-04-10T18:06:17Z" duration-ms="85001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FirstTask -->
        <test-method is-config="true" signature="closing()[pri:0, instance:Test.Test1@38d8f54a]" started-at="2018-04-10T18:06:17Z" name="closing" finished-at="2018-04-10T18:06:17Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closing -->
      </class> <!-- Test.Test1 -->
      <class name="Test.Test3">
        <test-method is-config="true" signature="launching()[pri:0, instance:Test.Test3@7c7b252e]" started-at="2018-04-10T18:02:15Z" name="launching" finished-at="2018-04-10T18:02:17Z" duration-ms="2409" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching -->
        <test-method signature="thirdTest()[pri:0, instance:Test.Test3@7c7b252e]" started-at="2018-04-10T18:02:17Z" name="thirdTest" finished-at="2018-04-10T18:04:50Z" duration-ms="152367" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method is-config="true" signature="closing()[pri:0, instance:Test.Test3@7c7b252e]" started-at="2018-04-10T18:04:50Z" name="closing" finished-at="2018-04-10T18:04:50Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closing -->
      </class> <!-- Test.Test3 -->
      <class name="Test.Test2">
        <test-method is-config="true" signature="launching()[pri:0, instance:Test.Test2@7cc0cdad]" started-at="2018-04-10T17:58:57Z" name="launching" finished-at="2018-04-10T17:58:59Z" duration-ms="2232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launching -->
        <test-method signature="SecondTask()[pri:0, instance:Test.Test2@7cc0cdad]" started-at="2018-04-10T17:58:59Z" name="SecondTask" finished-at="2018-04-10T18:02:15Z" duration-ms="195920" status="FAIL">
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[begin 0, end -4, length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: begin 0, end -4, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107)
	at java.base/java.lang.String.substring(String.java:1873)
	at Test.Test2.SecondTask(Test2.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SecondTask -->
        <test-method is-config="true" signature="closing()[pri:0, instance:Test.Test2@7cc0cdad]" started-at="2018-04-10T18:02:15Z" name="closing" finished-at="2018-04-10T18:02:15Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closing -->
      </class> <!-- Test.Test2 -->
    </test> <!-- Test -->
  </suite> <!-- suite -->
</testng-results>
